apiVersion: v1
kind: Service
metadata:
  name: ams
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-478a7c21, subnet-0072da0e
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: ams
  ports:
  - port: 80
    targetPort: http
    name: http 
    protocol: TCP
